### stage I

FROM node:14-slim AS builder

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install 

COPY . .

ARG BASE_URL
ARG REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

### stage II

FROM nginx:1.19.0-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /usr/src/app/build .

ENTRYPOINT ["nginx" , "-g" , "daemon off;"]
