version: "3.8"
services:
  react-app:
    image: react-app-production
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-app

  api-server:
    image: api-server
    restart: unless-stopped
    stdin_open: true
    ports: 
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local